### ISSUE TITLE
Calculating of the speed and rotation

### ISSUE THREAD

**Issue by akahan** [Patryk27/shorelark#9]
Hi! Can you explain why when you calculate a new angle and speed, you add the results of the neural network calculation (r0 and r1) for the speed, and subtract the results for the angle? Link below.

https://github.com/Patryk27/shorelark/blob/7b703d4e11501ce55bc240d85fd25e1c93dbbbd2/libs/simulation/src/brain.rs#L32

**Comment by Patryk27** [comment]
Hi!

In this model you can imagine birds as vehicles with two motors - kinda like:

![image](https://user-images.githubusercontent.com/3395477/216536962-812c50ec-bd1d-4e5a-a810-395cd29a47ec.png)

... where `r0` determines the speed of the "left motor" and `r1` determines speed of the "right motor", making:

- `rotation = r0 - r1`, since you just rotate away from whichever side is moving faster,
- `speed = r0 + r1`; although - now that I look at it - this one is probably kinda wrong (should be `(r0 + r1) / 2`?), because if we imagine both `r0` and `r1` going at 10 units per second, then in reality the entire bird would be moving at 10 units per second as well; fortunately, it shouldn't affect the computations much either way 😇 

As for "but why" - if I recall correctly, modeling it this way has gotten me a bit better results (i.e. better-flying, faster-learning birds) than the simpler approach where you'd just extract speed & rotation directly from the network, like so:

```rust
crate fn propagate(&self, vision: Vec<f32>) -> (f32, f32) {
    let response = self.nn.propagate(vision);

    let speed = response[0].clamp(0.0, 1.0) - 0.5;
    let rotation = response[1].clamp(0.0, 1.0) - 0.5;

    (speed, rotation)
}
```

Lemme know if it makes sense now! 🙂

**Comment by Patryk27** [comment]
Hi, to keep the issue tracker tidy, I'm going to close this issue - if you have any more questions, feel free to ask them here 🙂
